#!/usr/bin/env python3
"""
apply_op_config.py — 生成算子替换环境变量配置（仅 plugin 场景）

根据优化器输出的 blacklist 生成 env_config.sh，
服务启动前 source 此文件即可。

注意：此脚本不写入算子列表 txt 文件。txt 文件由 FlagGems 运行时自动生成。
重启服务后可通过 find_ops_list_file() 读取 txt 文件验证环境变量是否生效。

Usage:
    python apply_op_config.py --mode native
    python apply_op_config.py --mode full
    python apply_op_config.py --mode custom \
        --oot-blacklist "fused_moe" \
        --flagos-blacklist "softmax,layer_norm"
    python apply_op_config.py --from-state /path/to/operator_config.json
"""

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path

ENV_CONFIG_PATH = "/flagos-workspace/env_config.sh"


def generate(mode, oot_blacklist=None, flagos_blacklist=None, per_op=None,
             output=ENV_CONFIG_PATH):
    """
    生成环境变量配置文件（仅 plugin 场景使用）。

    mode:
      "native"  -> VLLM_FL_PREFER_ENABLED=false（关闭一切）
      "full"    -> VLLM_FL_PREFER_ENABLED=true（全量启用）
      "custom"  -> 按 blacklist 自定义
    """
    lines = [
        "#!/bin/bash",
        f"# Auto-generated by apply_op_config.py at {datetime.now().isoformat()}",
        f"# Mode: {mode}",
    ]

    if mode == "native":
        lines.append("export VLLM_FL_PREFER_ENABLED=false")
    elif mode == "full":
        lines.append("export VLLM_FL_PREFER_ENABLED=true")
        lines.append("unset VLLM_FL_FLAGOS_BLACKLIST")
        lines.append("unset VLLM_FL_OOT_BLACKLIST")
        lines.append("unset VLLM_FL_PER_OP")
    elif mode == "custom":
        lines.append("export VLLM_FL_PREFER_ENABLED=true")
        if oot_blacklist:
            bl = ",".join(oot_blacklist) if isinstance(oot_blacklist, list) else oot_blacklist
            lines.append(f'export VLLM_FL_OOT_BLACKLIST="{bl}"')
        else:
            lines.append("unset VLLM_FL_OOT_BLACKLIST")
        if flagos_blacklist:
            bl = ",".join(flagos_blacklist) if isinstance(flagos_blacklist, list) else flagos_blacklist
            lines.append(f'export VLLM_FL_FLAGOS_BLACKLIST="{bl}"')
        else:
            lines.append("unset VLLM_FL_FLAGOS_BLACKLIST")
        if per_op:
            lines.append(f'export VLLM_FL_PER_OP="{per_op}"')
    else:
        print(f"ERROR: unknown mode '{mode}'", file=sys.stderr)
        sys.exit(1)

    Path(output).parent.mkdir(parents=True, exist_ok=True)
    with open(output, 'w') as f:
        f.write('\n'.join(lines) + '\n')

    print(json.dumps({
        "success": True,
        "mode": mode,
        "output": output,
        "oot_blacklist": oot_blacklist or [],
        "flagos_blacklist": flagos_blacklist or [],
    }, indent=2, ensure_ascii=False))


def from_state(state_path, output=ENV_CONFIG_PATH):
    """从 operator_config.json 状态文件生成配置。"""
    with open(state_path, 'r', encoding='utf-8') as f:
        state = json.load(f)

    oot_blacklist = state.get("oot_blacklist", [])
    flagos_blacklist = state.get("flagos_blacklist", [])

    if not oot_blacklist and not flagos_blacklist:
        # 无 blacklist = full 模式
        generate("full", output=output)
    else:
        generate("custom", oot_blacklist=oot_blacklist,
                 flagos_blacklist=flagos_blacklist, output=output)


def main():
    parser = argparse.ArgumentParser(
        description="生成算子替换环境变量配置（仅 plugin 场景）")

    parser.add_argument("--mode", choices=["native", "full", "custom"],
                        help="配置模式")
    parser.add_argument("--oot-blacklist",
                        help="OOT 层 blacklist（逗号分隔）")
    parser.add_argument("--flagos-blacklist",
                        help="FlagOS 层 blacklist（逗号分隔）")
    parser.add_argument("--per-op",
                        help="逐算子控制（如 rms_norm=vendor;attention_backend=vendor）")
    parser.add_argument("--from-state",
                        help="从 operator_config.json 生成")
    parser.add_argument("--output", default=ENV_CONFIG_PATH,
                        help=f"输出文件路径（默认 {ENV_CONFIG_PATH}）")

    args = parser.parse_args()

    if args.from_state:
        from_state(args.from_state, args.output)
    elif args.mode:
        oot_bl = args.oot_blacklist.split(",") if args.oot_blacklist else None
        flagos_bl = args.flagos_blacklist.split(",") if args.flagos_blacklist else None
        generate(args.mode, oot_blacklist=oot_bl, flagos_blacklist=flagos_bl,
                 per_op=args.per_op, output=args.output)
    else:
        parser.print_help()
        sys.exit(1)


if __name__ == "__main__":
    main()
